### ISSUE TITLE
Sufficient code to reproduce your work

### ISSUE THREAD

**Issue by martianxiu** [Andy20178/SGFormer#3]
Hi, great work and thanks for providing the implementation! We would like to reproduce your work so that we can develop from it. Do you have any plans to release more details about your implementation?

**Comment by Andy20178** [comment]
Thank you for your interest in our work! Since this is my first project since enrolling in school, all my codes are relatively messy. I plan to organize my codes and make them open to the public after the CVPR2024 submission is over.
